[package]
name = "cleanroom"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi-escapes = "0.1"
ansi_term = "0.12"
anyhow = "1.0"
clap = { version = "4.3", features = ["derive"] }
