[package]
name = "contained_command"
description = "Run a command inside a container"
version = "0.1.0"

[dependencies]
util = { path = "../util" }

thiserror = { version = "1.0" }
tokio = { version = "1.32", default-features = false, features = ["process"] }
