[command]
help = """
Generate an arch linux based initrd

Note that modules will be added separately!
"""

script = """
    if [ "${CURRENT_PHASE}" = "${PHASE_PREPARE}" ]; then
        export_constant CLRM_BASE_DISTRIBUTION "arch"
        export_var PACKAGES ""

        bb_mkdir /sysroot

        export_var ENABLED_SYSTEMD_UNITS ""
    fi

    if [ "${CURRENT_PHASE}" = "${PHASE_INSTALL}" ]; then
        export_constant PACKAGES "${PACKAGES}"
        export_constant ENABLED_SYSTEMD_UNITS "${ENABLED_SYSTEMD_UNITS}"
    fi

    add_packages systemd

    hook_arch_extra_initrd_packages

    export_cpio initrd.cpio
"""
