[command]
help = """
Install a very basic Arch Linux -- just the basics
"""

script = """
    # gnutls is needed by systemd-resolved
    # sed and gzip by locale-gen
    # kitty-terminfo has some modern terminfo config (and is tiny)
    # zstd is modern compression, I want that
    # ca-certificates are needed for literally every secure connection
    add_packages \
        ca-certificates \
        gnutls \
        gzip \
        kitty-terminfo \
        sed \
        systemd \
        which \
        zstd

    if [ "${CURRENT_PHASE}" = "${PHASE_POLISH}" ]; then
        # polish away files that make no sense in an immutable setup (or are handled by us!)
        rm -f \
            /usr/lib/factory/tmpfiles.d/man-db.conf \
            /usr/lib/tmpfiles.d/arch.conf
    fi
"""
