[command]
help = """
Ensure the HWDB is up-to-date
"""

script = """
    if [ "${CURRENT_PHASE}" = "${PHASE_POLISH}" ]; then
        if [ -x /usr/bin/systemd-hwdb ]; then
            echo "Updating HWDB"
            /usr/bin/systemd-hwdb --usr update

            rm -f /usr/bin/systemd-hwdb
        fi
    fi
"""
