[command]
help = """
Export the entire root fs into the artifacts directory
"""

script = """
    echo "_export_root_fs: Start"
    if [ "${CURRENT_PHASE}" = "${PHASE_BUILD_ARTIFACTS}" ]; then
        version_dir="${ARTIFACTS_DIR}/${HOST_NAME}/${VERSION}"
        echo "_export_root_fs: version dir: ${version_dir}"

        bb_mkdir -p "${version_dir}"
        echo "_export_root_fs: version dir created"
        echo "_export_root_fs: Moving ${ROOT_FS} moved to ${version_dir}"
        mv "${ROOT_FS}" "${version_dir}"
    fi
    echo "_export_root_fs: End"
"""
