[command]
inputs = [{ name = "distribution_id", help = "The base distribution id" }]
help = """
Install packages for arch linux distributions
"""

script = """
    if [ "${CURRENT_PHASE}" = "${PHASE_INSTALL}" ]; then
        error "pacstrap is not supported yet!"
    fi
"""
