[command]
inputs = [{ name = "distribution_id", help = "The base distribution id" }]
help = """
Set the base distribution to use for cleanroom.
\t\t\t\tPossible values are \"arch\".
"""

script = """
    if [ "${CURRENT_PHASE}" = "${PHASE_PREPARE}" ]; then
        export_var PACKAGES ""
        export_var KERNEL_CMDLINE ""

        export_constant OS_RELEASE_NAME "cleanroom"
        export_constant OS_RELEASE_PRETTY_NAME "cleanroom Linux"
        export_constant OS_RELEASE_ID "clrm"

        if [ "${distribution_id}" == "arch" ]; then
            _distribution_arch
        elif [ "${distribution_id}" == "serpentos" ]; then
            _distribution_serpentos
        else
           error "Unknown base distribution id ${distribution_id} provided"
        fi

        export_constant CLRM_BASE_DISTRIBUTION "${distribution_id}"

        export_var PACKAGES ""
    elif [ "${CURRENT_PHASE}" = "${PHASE_INSTALL}" ]; then
        export_constant PACKAGES "${PACKAGES}" # Make PACKAGES ro from here on out!

        if [ "${distribution_id}" == "arch" ]; then
            _pacstrap
        elif [ "${distribution_id}" == "serpentos" ]; then
            _moss
        else
           error "Unknown base distribution id ${distribution_id} provided"
        fi
    fi
"""
