[command]
help = """
Export the entire root fs into the artifacts directory
"""
inputs = [ { name = "usr_only", help = "Only store /usr (on/off)"}]

script = """
    if [ "${CURRENT_PHASE}" = "${PHASE_BUILD_ARTIFACTS}" ]; then
        if [ "${usr_only}" = "on" -o "${usr_only}" = "ON" ]; then
            ( cd "${ROOT_FS}" && \
                bb_mkdir -p usr/lib/boot && \
                tar -cf usr/lib/boot/root-fs.tar efi etc root && \
                tar -cf usr/lib/boot/var-fs.tar var && \
                "${BUSYBOX}" find . ! -name usr -maxdepth 1 -exec rm -rf {} \\; )
        fi

        cp --reflink=auto -r "${ROOT_FS}" "${ARTIFACTS_DIR}/root_fs"

        export_constant ARTIFACT_ROOT_FS "${ARTIFACTS_DIR}/root_fs"
    fi
"""
