[command]
help = """
Generate and export a dm-verity image for a ARTIFACT_ROOT_IMAGE.
"""

script = """
    export_root_image

    if [ "${CURRENT_PHASE}" = "${PHASE_BUILD_ARTIFACTS}" ]; then
        test -x /usr/bin/veritysetup || error "veritysetup not found"

        vrty_image="${ARTIFACTS_DIR}/vrty.img"

        output=$(/usr/bin/veritysetup format "${ARTIFACT_ROOT_IMAGE}" "${vrty_image}")

        root_hash=$(echo "${output}" | "${BUSYBOX}" grep "^Root hash:" | "${BUSYBOX}" sed "s/Root hash:\\s\\+//")
        uuid=$(echo "${output}" | "${BUSYBOX}" grep "^UUID:" | "${BUSYBOX}" sed "s/UUID:\\s\\+//")

        test -z "${root_hash}" && error "Failed to extract root hash from veritysetup output"
        test -z "${uuid}" && error "Failed to extract uuid from veritysetup output"

        export_constant "ARTIFACT_VRTY_IMAGE" "${vrty_image}"
        export_constant "ARTIFACT_VRTY_ROOT_HASH" "${root_hash}"
        export_constant "ARTIFACT_VRTY_UUID" "${uuid}"
    fi
"""
