[command]
help = """
Install a kernel
"""
inputs = [ { name="package_name", help = "The name of the package to install (default: Distribution default kernel)", optional = true } ]

script = """
    if [ "${distribution_id}" == "arch" ]; then
        add_packages "${package_name-linux}" --assume-installed=initramfs

        if [ "${CURRENT_PHASE}" = "${PHASE_POLISH}" ]; then
           kernel_version=$(cd /usr/lib/modules && ls | sort | tail -n1)
           kernel_path="/usr/lib/modules/${kernel_version}/vmlinuz"
           test -e "${kernel_path}" || error "Kernel not found at ${kernel_path}"

           export_constant KERNEL_VERSION "${kernel_version}"
           export_constant KERNEL_PATH "${kernel_path}"
        fi
    else
       error "Unknown base distribution id ${distribution_id} is not supported by pkg_kernel"
    fi
"""
