[command]
help = """
Install a kernel
"""
inputs = [ { name="package_name", help = "The name of the package to install (default: Distribution default kernel)", optional = true } ]

script = """
    if [ "${distribution_id}" == "arch" ]; then
        add_packages "${package_name-linux}" --assume-installed=initramfs

        if [ "${CURRENT_PHASE}" = "${PHASE_POLISH}" ]; then
           if [ -d "${ROOT_FS}/usr/lib/modules" ]; then
              kernel_version=$(cd "${ROOT_FS}/usr/lib/modules" && ls | sort | tail -n1)
              kernel_path="${ROOT_FS}/usr/lib/modules/${kernel_version}/vmlinuz"
              test -e "${kernel_path}" || error "Kernel not found at ${kernel_path}"

              export_constant KERNEL_VERSION "${kernel_version}"
              mv "${kernel_path}" "${ARTIFACTS_DIR}/vmlinuz"
              export_constant KERNEL_PATH "${ARTIFACTS_DIR}/vmlinuz"
           else
              error "No /usr/lib/modules directory: Can not find kernel I asked to install"
           fi
        fi
    else
       error "Unknown base distribution id ${distribution_id} is not supported by pkg_kernel"
    fi
"""
