[command]
help = """
Set a (hashed!) password for an account
"""
inputs = [
    { name = "user", help = "The user to set a password for" },
    { name = "password", help = "The hashed password to set" }
]

script = """
    if [ "${CURRENT_PHASE}" = "${PHASE_POLISH}" ]; then
        "${busybox}" usermod --password "${password}" "${user}"
    fi

    if [ "${CURRENT_PHASE}" = "${PHASE_TEST}" ]; then
        grep "${user}" /etc/shadow | grep ":${password}:" > /dev/null || error "Password for user ${user} not found"
    fi
"""
