# Copyright © Tobias Hunger <tobias.hunger@gmail.com>
# SPDX-License-Identifier: GPL-3.0-or-later

---
name: CI

on:
  push:
    branches: [main, "feature/*"]
  pull_request:
    branches: [main, "feature/*"]
  workflow_dispatch:

jobs:
  cargo_fmt:
    runs-on: ubuntu-latest

    env:
      RUSTFLAGS: "-D warnings"
    steps:
      - uses: actions/checkout@v3
      - name: Install rust (nightly)
        uses: ./.github/actions/setup-rust
        with:
          toolchain: nightly
          components: rustfmt
          key: cargo_fmt
      - name: cargo version
        run: cargo +nightly --version
      - name: Run cargo fmt
        run: cargo +nightly fmt --check

  cargo_check:
    strategy:
      matrix:
        rust_version: [stable, nightly]
        os: [ubuntu-latest]

    runs-on: ${{matrix.os}}

    env:
      RUSTFLAGS: "-D warnings"
    steps:
      - uses: actions/checkout@v3
      - name: Install rust (${{matrix.rust_version}})
        uses: ./.github/actions/setup-rust
        with:
          toolchain: ${{matrix.rust_version}}
          key: cargo_check
      - name: cargo version
        run: cargo +${{matrix.rust_version}} --version
      - name: Run cargo check
        run: cargo +${{matrix.rust_version}} check

  cargo_clippy:
    runs-on: ubuntu-latest

    env:
      RUSTFLAGS: "-D warnings"
    steps:
      - uses: actions/checkout@v3
      - name: Install rust (nightly)
        uses: ./.github/actions/setup-rust
        with:
          toolchain: nightly
          components: clippy
          key: cargo_clippy
      - name: cargo version
        run: cargo +nightly --version
      - name: Run cargo clippy
        run: cargo +nightly clippy

  cargo_test:
    strategy:
      matrix:
        rust_version: [stable, nightly]
        os: [ubuntu-latest]

    runs-on: ${{matrix.os}}

    env:
      RUSTFLAGS: "-D warnings"
    steps:
      - uses: actions/checkout@v3
      - name: Install rust (${{matrix.rust_version}})
        uses: ./.github/actions/setup-rust
        with:
          toolchain: ${{matrix.rust_version}}
          key: cargo_test
      - name: cargo version
        run: cargo +${{matrix.rust_version}} --version
      - name: Run cargo test
        run: cargo +${{matrix.rust_version}} test

  spellcheck: # run the action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: streetsidesoftware/cspell-action@v3

  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --check --ignore-unknown .

  sh-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: luizm/action-sh-checker@master
